# templates/mongo/mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-env
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.user | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.password | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.mongo.db | quote }}