# templates/mongo/mongo-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      name: mongo
      port: 27017
      targetPort: 27017
  {{ if .Values.mongo.service.nodePort.enable }}
  type: NodePort
  {{ end }}