# templates/postgres/postgres-svc.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  {{ if .Values.postgres.service.nodePort.enable }}
  type: NodePort
  {{ end }}