# templates/fastgpt/fastgpt-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: fastgpt-env
type: Opaque
stringData:
  DEFAULT_ROOT_PSW: {{ .Values.fastgpt.rootPsw | quote }}
  {{- if .Values.fastgpt.openaiBaseUrl }}
  OPENAI_BASE_URL: {{ .Values.fastgpt.openaiBaseUrl }}
  {{- else }}
  OPENAI_BASE_URL: http://oneapi.{{ .Release.Namespace }}.svc/v1
  {{- end }}
  CHAT_API_KEY: {{ .Values.fastgpt.chatApiKey | quote }}
  DB_MAX_LINK: {{ .Values.fastgpt.dbMaxLink | quote }}
  TOKEN_KEY: {{ .Values.fastgpt.tokenKey | quote }}
  ROOT_KEY: {{ .Values.fastgpt.rootKey | quote }}
  FILE_TOKEN_KEY: {{ .Values.fastgpt.fileTokenKey | quote }}
  MONGODB_URI: "mongodb://{{ .Values.mongo.user }}:{{ .Values.mongo.password }}@mongo:27017/{{ .Values.mongo.db }}?authSource=admin"
  PG_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.db }}"
