# templates/fastgpt/fastgpt-ing.yaml
{{- if .Values.fastgpt.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastgpt-ingress
spec:
  rules:
    - host: {{ .Values.fastgpt.ingress.domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: fastgpt
                port:
                  number: 80
{{- end }}
